# test spreadsheet

In [1]:
import os
import sys
import numpy as np
import pandas as pd

In [5]:
column_names = ['one_lane', 'two_lane', 'trim', 'dedupe', 'Bqsr', 'Vqsr', 'who']
test_spreadsheet = pd.DataFrame(data=np.zeros((16,7)),columns=column_names)
test_spreadsheet

    one_lane  two_lane  trim  dedupe  Bqsr  Vqsr  who
0        0.0       0.0   0.0     0.0   0.0   0.0  0.0
1        0.0       0.0   0.0     0.0   0.0   0.0  0.0
2        0.0       0.0   0.0     0.0   0.0   0.0  0.0
3        0.0       0.0   0.0     0.0   0.0   0.0  0.0
4        0.0       0.0   0.0     0.0   0.0   0.0  0.0
5        0.0       0.0   0.0     0.0   0.0   0.0  0.0
6        0.0       0.0   0.0     0.0   0.0   0.0  0.0
7        0.0       0.0   0.0     0.0   0.0   0.0  0.0
8        0.0       0.0   0.0     0.0   0.0   0.0  0.0
9        0.0       0.0   0.0     0.0   0.0   0.0  0.0
10       0.0       0.0   0.0     0.0   0.0   0.0  0.0
11       0.0       0.0   0.0     0.0   0.0   0.0  0.0
12       0.0       0.0   0.0     0.0   0.0   0.0  0.0
13       0.0       0.0   0.0     0.0   0.0   0.0  0.0
14       0.0       0.0   0.0     0.0   0.0   0.0  0.0
15       0.0       0.0   0.0     0.0   0.0   0.0  0.0

In [6]:
test_spreadsheet.to_csv('test_matrix.tsv', sep='\t')